#!/bin/sh
cd "${0%/*}" || exit                                # Run from this directory
#------------------------------------------------------------------------------

set -e

# Note
# Make all <All*> and <run*> files executable 
find ./* -type f -name "All*" -exec chmod +x {} \;
find ./* -type f -name "run*" -exec chmod +x {} \;


#------------------------------------------------------------------------------
